name: Build exe

on: workflow_dispatch

env:
  TARGET: CoolLab # Should be the name of the target you created in your CMakeLists.txt and want to build and run


jobs:

  Create_tag:
    name: Create tag
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: refs/tags/alpha.1.0
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
#-----------------------------------------------------------------------------------------------
  Windows_Clang_Release:
    needs: Create_tag
    name: Windows Clang Release
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v3
      with:
          submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}\build -T ClangCL

    - name: Build
      run: cmake --build ${{github.workspace}}\build --config Release --target ${{env.TARGET}}

    - name: Zip file
      run: 7z a Windows_Release.zip ${{github.workspace}}\bin\Release

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Windows_Release.zip
#-----------------------------------------------------------------------------------------------
  Linux_Clang_Release:
    needs: Create_tag
    name: Linux Clang Release
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Install glfw dependencies
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev mesa-common-dev build-essential libgtk-3-dev    

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=clang -D CMAKE_CXX_COMPILER=clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target ${{env.TARGET}}

    - name: Zip building directory
      run: |
            cd ${{github.workspace}}/bin
            tar -zcvf Linux_Release.zip ./Release
            
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: Linux_Release.zip

#-----------------------------------------------------------------------------------------------
  MacOS_Clang_Release:
    needs: Create_tag
    name: MacOS Clang Release
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -D CMAKE_BUILD_TYPE=Release -D CMAKE_C_COMPILER=/usr/local/opt/llvm/bin/clang -D CMAKE_CXX_COMPILER=/usr/local/opt/llvm/bin/clang++

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release --target ${{env.TARGET}}
      
    - name: Zip building directory
      run: |
            cd ${{github.workspace}}/bin
            zip MacOS_Release.zip ./Release

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: MacOS_Release.zip

